### ISSUE TITLE
build fails - missing <cstdint>

### ISSUE THREAD

**Issue by incompetentcoder** [tristanpenman/chaos#1]
Heya - build fails with undefined uint types due to missing <cstdint> in KosinskiReader.h - just include and fixed

**Comment by tristanpenman** [comment]
Have just added this in commit https://github.com/tristanpenman/chaos/commit/bf4269c52c89e356c225a22137af730fea78cedf

Let me know if that fixes it for you.

**Comment by incompetentcoder** [comment]
cheers! almost forgot another thing i had to do for building - -Werror causes it to fail in chaos/src/Block.cpp:8:9: error: ‘void* memset(void*, int, size_t ’ clearing an object of type ‘class ChunkDesc’ with no trivial copy-assignment; use value-initialization instead [-Werror=class-memaccess]  - but disabling -Werror does fix the cstdint issue with your commit thanks for the quick reply!

**Comment by tristanpenman** [comment]
Ah, thanks for the heads up. Your post came at just the right time, while I was taking my lunch break. I should be able to have a look at the other issue tonight.

**Comment by tristanpenman** [comment]
By the way, which platform and compiler are you using?

**Comment by incompetentcoder** [comment]
no hurries it's both simple enough to fix and obvious enjoy your lunch! i'll still close this now as cstdint is fixed and werror will be a larger undertaking fixing all warnings. cheers o/

**Comment by incompetentcoder** [comment]
oh
Target: x86_64-pc-linux-gnu
gcc version 12.2.1 20230201 (GCC)

**Comment by tristanpenman** [comment]
Warnings have been fixed in ff6e9d26c03d5172958a8fed159fee407fe309db 😄

**Comment by incompetentcoder** [comment]
nice!
